language: node_js
node_js:
- '8'
- '10'
env:
  global:
    - secure: "A6aMc3nfEJwNb8dGkrt51LlVvvBN6euqHziPFsDu/VuqPgL69CI5RQGB1rNYrxRcpVmn+kz9dENz93F08RfGiBi4ytoqLb5kE+vYze8GNwJatEOJTfYe/jfGcgPoCp4HDpLmif1Rl8rfPWiB1TpdcNBv2Hm8CuqJZj2mTHveVE4="
cache:
  directories:
  - node_modules
after_success:
  - "[[ $TRAVIS_BRANCH = 'master' ]] && [[ $TRAVIS_NODE_VERSION = '0.10' ]] && ./node_modules/codeclimate-test-reporter/bin/codeclimate.js < coverage/lcov.info"
